name: Jupyter Notebook check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  jupyter_notebook_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: docker-compose build --no-cache
      - name: Run jupyter notebooks
        working-directory: ./docker
        run: |
          for f in $(find work/ -type f -name "*.ipynb"); do
            docker exec notebook jupyter nbconvert --to notebook --execute ${f}
          done
